---

  ## Local playbook to build an uberjar using lein.
  ## This step can (and should) also be done with Jenkins for instance.

- name: "Ensure temp path /tmp/{{ app_name }} is clean"
  file: path=/tmp/{{ app_name }} state=absent

- name: "Clone {{ app_repo }} repo in a temp directory"
  git: repo=https://github.com/{{ app_repo }} dest=/tmp/{{ app_name }}

- name: "Run lein uberjar in the temp directory"
  shell: lein do clean, uberjar
  args:
    chdir: /tmp/{{ app_name }}
