---

  ## Local playbook to build an uberjar using lein.
  ## This step can (and should) also be done with Jenkins for instance.


# Ensure temp path is clean
- file: path=/tmp/{{ app_name }} state=absent
# Clone the repo in a temp directory
- git: repo=https://github.com/{{ app_repo }} dest=/tmp/{{ app_name }}
# Run lein uberjar in the temp directory
- shell: lein do clean, uberjar
  args:
    chdir: /tmp/{{ app_name }}
# Retrieve the exact filename
- find: paths=/tmp/{{ app_name }}/target/ patterns="*standalone*"
  register: st
# Set a fact with the path to the jar just built
- set_fact: app_jar={{ st.files[0].path }}
