---

- name: "Setup security group"
  action: ec2_group
  args:
    name: "{{ app_name }}-instances-sg"
    description: "Instances for {{ app_name }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 3003
        to_port: 3003
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        from_port: -1 # icmp type, -1 = any type
        to_port:   -1 # icmp subtype, -1 = any subtype
        cidr_ip: 0.0.0.0/0
      - proto: all
        group_name: "{{ app_name }}-instances-sg"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: "Launch {{ app_name }} instances"
  action: ec2
  args:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami }}"
    region: "{{ ec2_region }}"
    group: "{{ app_name }}-instances-sg"
    count: "{{ app_count }}"
    wait: true
    wait_timeout: 500
    instance_tags:
      toyinstance: pguillebert
      env: dev
  register: ec2

- name: "Wait for all SSH to come up"
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances
